user: f4c8620816b74f7a9ccf184ece74117f
password: Sensoro2021A#BaoDingA#365
server: https://openai-api.dianjun.sensoro.vip
url_map:
  FULL_TARGET: "/v1/whole/target/detect"  # 全目标
  BOAT_DETECT: "/v1/boat/detect"  # 船只识别
  FISHING_DETECT: "/v1/fishing/detect"  # 非法捕鱼
file_path:  # 文件所在根目录
  ship: /Users/sunzhaohui/Desktop/升哲测试数据/船只测试集合/
  full: /Users/sunzhaohui/Desktop/升哲测试数据/全目标/
  fish: /Users/sunzhaohui/Desktop/升哲测试数据/捕鱼/
ship_result: /Users/sunzhaohui/Desktop/升哲测试数据/船只测试集合/船只记录.xlsx
num: 73  # 文件写入Excel时使用，每次写入后更新
column: 7   # 记录结果列，每次运行后更新