server: # 平台不同环境及地址
  DianJun:
    url: https://ai-api.dianjun.sensoro.vip/api/user/v1/passwordLogin
    user: mlxcsophia
    password: Sensoro20192020
  test:
    url: https://ivms-test1-api.sensoro.com/api/user/v1/passwordLogin
    user: szh_test_ams
    password: Sensoro2022

sdk: # 算法sdk地址及用户名
  DianJun:
    url: https://openai-api.dianjun.sensoro.vip
    user: f4c8620816b74f7a9ccf184ece74117f
    password: Sensoro2021A#BaoDingA#365
  pre:
    url: https://openai-pre-api.dianjun.sensoro.vip
    user: f4c8620816b74f7a9ccf184ece74117f
    password: Sensoro2021A#BaoDingA#365

url_map:  # 算法url
  v1:
    full: "/v1/whole/target/detect"  # 全目标
    boat: "/v1/boat/detect"  # 船只识别
    fish: "/v1/fishing/detect"  # 非法捕鱼
    tarsh: "/v1/trash/status/detect"  # 垃圾桶状态识别
    face_detect: "/v1/human/face/detect"  # 人脸检测
    face_match: "/v1/human/face/match"  # 人脸比对（一对一）
  v2: # v2目前仅支持全目标
    full: "/v2/whole/target/detect"  # 全目标

time: # 下载视频起止时间
  startTime: 2022-03-01 00:00:00
  endTime: 2022-03-09 07:03:48
size: 400 # 查询数量

database:
  host: localhost
  port: 3306
  user: root
  # 不用''会被解析成int类型数据
  password: '11111111'
  db_name: sensoro
  charset: utf8

  # 数据库所在的服务器配置
  ssh_server:
    port: 22
    username: root
    password: '123456'
    # 私有密钥文件路径
    private_key_file:
    # 私钥密码
    privat_passowrd:
    # 如果使用的docker容器部署mysql服务，需要传入mysql的容器id/name
    mysql_container: mysql8
    # 数据库备份文件导出的本地路径, 需要保证存在该文件夹
    sql_data_file: backup_sqls/


